acc_in_g: false # 加速度是否以g为单位
gravity_mag: 9.81 # 重力向量模长（m/s²）

noise_params:
    prior_roll_pitch_std: 0.01 # 先验横滚俯仰角标准差（rad）
    prior_yaw_std: 0.01 # 先验航向角标准差（rad）
    prior_pos_std: 0.1 # 先验位置标准差（m）
    prior_vel_std: 0.1 # 先验速度标准差（m/s）
    prior_gyr_bias_std: 0.1 # 先验陀螺仪零偏标准差（rad/s）
    prior_acc_bias_std: 0.1 # 先验加速度计零偏标准差（m/s^2）

    gyr_std: 1e-2 # 陀螺仪标准差（rad/s/√Hz）
    acc_std: 1e-1 # 加速度计标准差 (m/s^2/√Hz）
    gyr_bias_std: 1e-3 # 陀螺仪零偏标准差（rad/s）
    acc_bias_std: 1e-2 # 加速度计零偏标准差（m/s^2）
    integration_std: 1e-1 # 积分标准差（m/s）
    init_bias_std: 1e-2 # 初始零偏标准差（rad/s、m/s^2）

    odom_rot_std: 1e-2 # 里程计姿态角标准差（rad）
    odom_trans_std: 1e-1 # 里程计位移标准差（m）

    ext_rot_std: 2e-4 # 外参姿态角标准差（rad）
    ext_trans_std: 2e-3 # 外参位移标准差（m）

lidar_rig_file: "config/calibration/f400.yaml" # 雷达配置文件（支持相对yl_slam的路径）
camera_rig_file: "" # 相机配置文件（支持相对yl_slam的路径）

drawer:
    # 话题发布名称
    topic:
        current_nav_state: "current_nav_state"
        frame_point_clouds:
            - "lidar0/point_cloud"
        frame_compress_point_clouds:
            - "lidar0/compress_point_cloud"
        submap: "submap"
        reset: "reset"
    # 坐标系id
    frame_id:
        lidars:
            - "lidar0"
        imu: "imu0"
        map: "map"

preprocessor:
    point_cloud:
        crop_box_size: 0.5 # 裁剪尺寸（m）
        voxel_grid_size: 0.2 # 体素尺寸（m）
        min_voxel_size: 0.2 # 最小体素尺寸（m）
        max_voxel_size: 1.0 # 最大体素尺寸（m）
        desire_point_cloud_size: 5000 # 期望点云大小

point_cloud_aligner:
    max_iterations: 10 # 最大迭代次数
    absolute_error_eps: 0.01 # 绝对误差收敛阈值
    relative_error_eps: 0.01 # 相对误差收敛阈值
    trans_eps: 1e-3 # 平移收敛阈值
    rot_eps: 1e-3 # 旋转收敛阈值
    num_threads: 4 # 线程数
    verbosity: false # 是否打印详细信息（需要编译时LOG等级为DEBUG）

eskf:
    max_iterations: 10 # IESKF最大迭代次数
    iteration_quit_eps: 1e-3 # IESKF迭代停止的最小步长
    verbosity: false # 是否打印详细信息（需要编译时LOG等级为DEBUG）

local_mapper:
    leaf_size: 0.5 # 体素尺寸（m）
    lru_horizon: 10 # LRU删除阈值
    lru_clear_cycle: 10 # LRU清除周期
    search_offset: 1 # 搜索偏移量
    voxel_content:
        min_dist_in_cell: 0.01 # 容器中最小的点间距离平方
        max_num_points_in_cell: 20 # 容器中最大点数

initializer:
    # type: "static" # 静态初始化器
    # parameters:
    #     rows: 3
    #     cols: 1
    #     data: [ 1.0, 0.02, 0.2 ] # 参数顺序 [初始化周期（s）、陀螺仪零速阈值（rad/s）、加速度零速阈值（m/s^2）]
    type: "dynamic" # 静态初始化器
    parameters:
        rows: 1
        cols: 1
        data: [ 10 ] # 参数顺序 [缓冲区阈值]

drift_detector:
    max_rot_err: 0.2 # 最大旋转误差（rad）
    max_trans_err: 0.5 # 最大位移误差（m）
    max_vel_err: 0.5 # 最大速度误差（m/s）
    verbosity: false # 是否打印详细信息（需要编译时LOG等级为DEBUG）

estimator:
    cov_estimation_neighbors: 5 # 点云协方差估计的最近邻数
    min_icp_points: 100 # 进行ICP的最小点数
    use_imu_prior: true # 是否使用IMU先验
    estimate_extrinsic: true # 是否估计外参